In [2]:
import numpy as np
### задание 1.1

In [3]:
a = np.array([range(12,24)])
print(a)
a.shape

[[12 13 14 15 16 17 18 19 20 21 22 23]]


(1, 12)

In [4]:
a.shape = (2,6)
print(a)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [5]:
a.shape = (3,4)
print(a)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [6]:
a.shape = (4,3)
print(a)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [7]:
a.shape = (6,2)
print(a)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [8]:
a.shape = (1,12)
print(a)

[[12 13 14 15 16 17 18 19 20 21 22 23]]


In [9]:
z=a.reshape(2,-1)
print(z)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [10]:
z=a.reshape(3,-1)
print(z)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [11]:
z=a.reshape(6,-1)
print(z)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [12]:
z=a.reshape(-1,6)
print(z)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [13]:
z=a.reshape(-1,1)
print(z)
z.shape
z.ndim

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


2

#### Так как команда ndim по отношению к массиву, состоящему из 1 столбца и 12 строк выдает значение 2, то данный массив является двумерным. Считать его одномерным нельзя. 

In [14]:
### задание 1.2
rnd=np.random.rand(3,4)
rnd

array([[0.92156827, 0.58870933, 0.95140232, 0.88874327],
       [0.64860787, 0.45589404, 0.2187226 , 0.14611643],
       [0.31867428, 0.47928932, 0.59064123, 0.25477339]])

In [15]:
rnd.reshape(1,-1)

array([[0.92156827, 0.58870933, 0.95140232, 0.88874327, 0.64860787,
        0.45589404, 0.2187226 , 0.14611643, 0.31867428, 0.47928932,
        0.59064123, 0.25477339]])

In [16]:
#### задание 1.3
a=np.arange(20,0,-2,)
print(a)
a.shape

[20 18 16 14 12 10  8  6  4  2]


(10,)

In [17]:
b=(np.arange(20,1,-2)).reshape(10,1)
print(b)
b.shape

[[20]
 [18]
 [16]
 [14]
 [12]
 [10]
 [ 8]
 [ 6]
 [ 4]
 [ 2]]


(10, 1)

In [18]:
### как видно из рещультата применения функции shape массив a является одномерным, массив b являеся двумерным

In [19]:
#### Задание 1.4.

In [20]:
a=np.zeros((3,2))
print(a)
b=np.ones((2,2))
print (b)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [21]:
v=np.vstack((a,b))
v.size

10

In [22]:
### задание 1.5
A=np.random.randint(0,12,(4,3))
print(A)

[[10  1  9]
 [10  2  2]
 [ 8  9 11]
 [ 9  8  5]]


In [23]:
At=A.transpose()
print(At)

[[10 10  8  9]
 [ 1  2  9  8]
 [ 9  2 11  5]]


In [24]:
B=np.dot(A,At)
print(B)
b.size


[[182 120 188 143]
 [120 108 120 116]
 [188 120 266 199]
 [143 116 199 170]]


4

In [25]:
### нахождение обратной матрицы для матрицы B
B_inv=np.linalg.inv(B)
print (B_inv)

[[-2.89393260e+13  4.38271874e+13  3.89760865e+13 -5.11874784e+13]
 [ 4.38271874e+13 -6.63741219e+13 -5.90273679e+13  7.75209210e+13]
 [ 3.89760865e+13 -5.90273679e+13 -5.24938043e+13  6.89403610e+13]
 [-5.11874784e+13  7.75209210e+13  6.89403610e+13 -9.05397016e+13]]


In [26]:
### задание 1.6
np.random.seed(42)
C=np.random.randint(0,16,16)
C=C.reshape(4,4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [27]:
D=(C*10)+B
print (D)
### определитель матрицы, ранг и обратная матрица D
print(np.linalg.det(D))
print(np.linalg.matrix_rank(D))
D_inv=np.linalg.inv(D)
print(D_inv)

[[242 150 308 283]
 [220 178 240 156]
 [248 210 286 259]
 [243 216 269 210]]
-3153599.9999999907
4
[[-0.09740804  0.22525495  0.31373224 -0.42299975]
 [ 0.01796169 -0.07282344 -0.08531329  0.13511162]
 [ 0.08790145 -0.16471461 -0.27112062  0.33828387]
 [-0.01835743  0.02524353  0.0720104  -0.07806443]]


In [28]:
#### задание 1.7
D_inv[D_inv>0]=1
D_inv[D_inv<0]=0        

print(D_inv)
print(D_inv.size)
            
        

[[0. 1. 1. 0.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [0. 1. 1. 0.]]
16


In [29]:
E=np.where(D_inv,B,C)
print(B)
print()
print(C)
print()
print(D_inv)
print()
print(E)

[[182 120 188 143]
 [120 108 120 116]
 [188 120 266 199]
 [143 116 199 170]]

[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]

[[0. 1. 1. 0.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [0. 1. 1. 0.]]

[[  6 120 188  14]
 [120   7  12 116]
 [188   9   2 199]
 [ 10 116 199   4]]


### Задание 2/.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
Будем считать, что каждый столбец - это признак, а строка - наблюдение.
Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [30]:
a=np.array([[1,6],
           [2,8],
           [3,11],
           [3,10],
           [1,7]])

In [31]:
a_mean = a.mean(axis=0)
print(a_mean)

[2.  8.4]


Задание 3
Вычислите массив a_centered, отняв от значений массива а средние значения соответствующих признаков, 
содержащиеся в массиве mean_a.
Вычисление должно производиться в одно действие.
Получившийся массив должен иметь размер 5x2.

In [32]:
a_centered=a-a_mean
print(a_centered)


[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


Задание 4
Найдите скалярное произведение столбцов массива a_centered.
В результате должна получиться величина a_centered_sp. 
Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [33]:
T=a_centered.transpose()
print(T)
A=(T[:1,:].copy()).flatten()
B=(T[1:,:].copy()).flatten()
a_centered_sp=A@B

print('Значение a_centered_sp :',a_centered_sp)
print('Отношение a_centered_sp к количеству наблюдений :',a_centered_sp/(len(A)-1))

[[-1.   0.   1.   1.  -1. ]
 [-2.4 -0.4  2.6  1.6 -1.4]]
Значение a_centered_sp : 8.0
Отношение a_centered_sp к количеству наблюдений : 2.0


Задание 5** Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве а. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации. В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив a. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [34]:
D=np.cov(a.transpose())
D

array([[1. , 2. ],
       [2. , 4.3]])

In [35]:
a_centered_sp/(len(A)-1)==D[0,1]

True