In [5]:
import numpy as np
### задание 1.1

In [19]:
a = np.array([range(12,24)])
print(a)
a.shape

[[12 13 14 15 16 17 18 19 20 21 22 23]]


2

In [7]:
a.shape = (2,6)
print(a)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [8]:
a.shape = (3,4)
print(a)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [9]:
a.shape = (4,3)
print(a)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [10]:
a.shape = (6,2)
print(a)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [11]:
a.shape = (1,12)
print(a)

[[12 13 14 15 16 17 18 19 20 21 22 23]]


In [12]:
z=a.reshape(2,-1)
print(z)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [13]:
z=a.reshape(3,-1)
print(z)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [14]:
z=a.reshape(6,-1)
print(z)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [15]:
z=a.reshape(-1,6)
print(z)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [18]:
z=a.reshape(-1,1)
print(z)
z.shape
z.ndim

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


2

#### Так как команда ndim по отношению к массиву, состоящему из 1 столбца и 12 строк выдает значение 2, то данный массив является двумерным. Считать его одномерным нельзя. 

In [32]:
### задание 1.2
rnd=np.random.rand(3,4)
rnd

array([[0.04690301, 0.08745139, 0.93325003, 0.25703341],
       [0.22874614, 0.10388194, 0.49528356, 0.08671648],
       [0.69340923, 0.66574198, 0.69597812, 0.38954606]])

In [33]:
rnd.reshape(1,-1)

array([[0.04690301, 0.08745139, 0.93325003, 0.25703341, 0.22874614,
        0.10388194, 0.49528356, 0.08671648, 0.69340923, 0.66574198,
        0.69597812, 0.38954606]])

In [54]:
#### задание 1.3
a=np.arange(20,0,-2,)
print(a)
a.shape

[20 18 16 14 12 10  8  6  4  2]


(10,)

In [55]:
b=(np.arange(20,1,-2)).reshape(10,1)
print(b)
b.shape

[[20]
 [18]
 [16]
 [14]
 [12]
 [10]
 [ 8]
 [ 6]
 [ 4]
 [ 2]]


(10, 1)

In [ ]:
### как видно из рещультата применения функции shape массив a является одномерным, массив b являеся двумерным

In [ ]:
#### Задание 1.4.

In [73]:
a=np.zeros((3,2))
print(zero_array)
b=np.ones((2,2))
print (one_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [74]:
v=np.vstack((a,b))
v.size

10

In [143]:
### задание 1.5
A=np.random.randint(0,12,(4,3))
print(A)




[[5 9 1]
 [9 0 3]
 [4 7 3]
 [0 7 3]]


In [144]:
At=A.transpose()
print(At)

[[5 9 4 0]
 [9 0 7 7]
 [1 3 3 3]]


In [145]:
B=np.dot(A,At)
print(B)
b.size


[[107  48  86  66]
 [ 48  90  45   9]
 [ 86  45  74  58]
 [ 66   9  58  58]]


30

In [146]:
### нахождение обратной матрицы для матрицы B
B_inv=np.linalg.inv(B)
print (B_inv)

[[-4.31946735e+13 -4.11377843e+13  1.46553357e+14 -9.10173478e+13]
 [-4.11377843e+13 -3.91788422e+13  1.39574625e+14 -8.66831884e+13]
 [ 1.46553357e+14  1.39574625e+14 -4.97234603e+14  3.08808859e+14]
 [-9.10173478e+13 -8.66831884e+13  3.08808859e+14 -1.91786554e+14]]


In [152]:
### задание 1.6
np.random.seed(42)
C=np.random.randint(0,16,16)
C=C.reshape(4,4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [281]:
D=(C*10)+B
print (D)
### определитель матрицы, ранг и обратная матрица D
print(np.linalg.det(D))
print(np.linalg.matrix_rank(D))
D_inv=np.linalg.inv(D)
print(D_inv)

[[ 61177  30528 120946 140726]
 [100528  70990 120495  40099]
 [ 60946  90495  20814  60638]
 [100726 100099  70638  40638]]
7.458616577743991e+18
4
[[ 2.90953654e-05 -1.06021369e-04 -1.06201073e-04  1.62328293e-04]
 [-2.42036748e-05  7.23561752e-05  7.88341194e-05 -1.05213526e-04]
 [-1.38898626e-05  6.16373425e-05  4.54970292e-05 -8.06087861e-05]
 [ 1.16456514e-05 -2.25801205e-05 -1.00355914e-05  2.15348320e-05]]


In [282]:
#### задание 1.7
for g in range(0,4):
    for h in range(0,4):
        if D_inv[g][h]<0:
            D_inv[g][h]=0
        elif D_inv[g][h]>0:
                D_inv[g][h]=1           

print(D_inv)
print(D_inv.size)
            
        

[[1. 0. 0. 1.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [1. 0. 0. 1.]]
16


In [284]:
E=np.where(D_inv>0,B,C)
print(B)
print()
print(C)
print()
print(D_inv)
print()
print(E)

[[107  48  86  66]
 [ 48  90  45   9]
 [ 86  45  74  58]
 [ 66   9  58  58]]

[[ 6107  3048 12086 14066]
 [10048  7090 12045  4009]
 [ 6086  9045  2074  6058]
 [10066 10009  7058  4058]]

[[1. 0. 0. 1.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [1. 0. 0. 1.]]

[[  107  3048 12086    66]
 [10048    90    45  4009]
 [ 6086    45    74  6058]
 [   66 10009  7058    58]]
